name: roofgriduk  # Changed from roofgridk_app
description: RoofGrid UK app for roof surveys and management.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  http: ^1.1.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_analytics: ^11.4.5
  flutter_animate: ^4.2.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  url_launcher: ^6.1.12
  go_router: ^14.8.1
  csv: ^6.0.0
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  share_plus: ^10.1.4
  flutter_riverpod: ^2.5.1
  google_sign_in: ^6.2.1
  in_app_purchase: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/